### ISSUE TITLE
Selecting Disabled

### ISSUE THREAD

**Issue by zaknafean** [MakovWait/improved_resource_picker#1]
Not fully sure if this is intended in some way, but the LineEdit doesn't allow the use of conventional short cuts (double click or ctrl+a for select all) and at least for me, was felt immediately. Its an easy fix though just requiring 'Selecting Enabled' to be turned on, and my 'power user short cuts' work fine

![image](https://user-images.githubusercontent.com/7741797/153480114-d2cb62e3-6e7e-4c07-a3bf-c8e290597b2e.png)

Made a PR for it, unless there is a reason its turned off on purpose.

**Comment by MakovWait** [comment]
Thanks!
