### ISSUE TITLE
Any reason why this isn't on the asset repository?

### ISSUE THREAD

**Issue by tavurth** [MakovWait/improved_resource_picker#3]
Just wondering :)

**Comment by belzecue** [comment]
Absolutely agree. This functionality should be part of the editor.  It is beyond insanity for any UI to present a very long list of scrollable items and no way to filter them to easily find what you need.  Out of a handful of strange design choices in Godot, this one I find to be the most bizarre.  Thankfully, this fantastic resource picker add-on is the next best thing and should be submitted to the AssetLib and made available in the editor.

**Comment by MakovWait** [comment]
Done :)

**Comment by belzecue** [comment]
> Done :)

You, sir, are a man of way too few words. ;)

Adding the Godot Asset Store page link for future visitors: https://godotengine.org/asset-library/asset/1362
